# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1130efaada049fc88613f8588150e69e5cccf42ba364c4267ca7e75c90d6ba4233694fe3a5c7723cba78904ba18f6d7fa572cbd15b6051fcc26b86b25d1521

test:
  secret_key_base: 54f4659a5c2cb857bb066725d208fecbdff4c94d755d2fc507c03cfd44232545692cdb51ab1a3e28abdc2df1c263f86da4283d96d4cd2b6f4593b7a10a78e3af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
